INSERT INTO "USERS" (ID, FIRST_NAME, LAST_NAME, EMAIL, CREATED_DATE) VALUES(4, 'mkyong','suepr','111@yahoo.com', TO_DATE('2017-02-11', 'yyyy-mm-dd'));
INSERT INTO "USERS" (ID, FIRST_NAME, LAST_NAME, EMAIL, CREATED_DATE) VALUES(2, 'yflow','travolta','222@yahoo.com', TO_DATE('2017-02-12', 'yyyy-mm-dd'));
INSERT INTO "USERS" (ID, FIRST_NAME, LAST_NAME, EMAIL, CREATED_DATE) VALUES(3, 'zilap','thebesciak','333@yahoo.com', TO_DATE('2017-02-13', 'yyyy-mm-dd'));
INSERT INTO "USERS" (ID, FIRST_NAME, LAST_NAME, EMAIL, CREATED_DATE) VALUES(1, 'zi4ap','ffucker','383@yahoo.com', TO_DATE('2017-02-13', 'yyyy-mm-dd'));
INSERT INTO "USERS" (ID, FIRST_NAME, LAST_NAME, EMAIL, CREATED_DATE) VALUES(5, 'zi4ap','ffucker','383@yahoo.com', sysdate);
-- INSERT INTO "TRAININGS" (ID, USER_ID, DURATION, ) VALUES(1, 2);
-- INSERT INTO "TRAININGS" (ID, USER_ID) VALUES(2, 1);
-- INSERT INTO "TRAININGS" (ID, USER_ID, CALORIES) VALUES(3, 1);
INSERT INTO "TRAININGS" (ID, CALORIES_PER_HOUR, DURATION, NAME, TYPE, USER_ID) VALUES (2, 40, 222, 'High press', 'bulk', 1)